apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: ln-hospspace-ufe-content
spec:
  microFrontend: ln-hospspace-ufe
  element: ln-hospspace-app
  attributes:
    - name: base-path
      value: /ln-hospspace-wl/
  displayRules:
    - allOf:
      - context-name: main-content
      - path: ".*hospspace.*"